import { BeforeAfterComparator } from "@/components/marketing/before-after-comparator";
import { FAQ } from "@/components/marketing/faq";
import { SelfServeForm } from "@/components/marketing/self-serve-form";
import { Card, CardContent } from "@/components/ui/card";
import { getSampleBeforeAfters } from "@/lib/samples";

export const dynamic = "force-dynamic";
export const metadata = { title: "Merchant — [Audience A funnel]" };

const STATS = [
  { figure: "[Stat 1]", label: "[label]", detail: "[Detail with source.]", source: "[Source]" },
  { figure: "[Stat 2]", label: "[label]", detail: "[Detail with source.]", source: "[Source]" },
  { figure: "[Stat 3]", label: "[label]", detail: "[Detail with source.]", source: "[Source]" },
  { figure: "[Stat 4]", label: "[label]", detail: "[Detail with source.]", source: "[Source]" },
];

export default async function AudienceAPage() {
  const samples = await getSampleBeforeAfters("audience-a");
  return (
    <>
      <section className="border-b bg-gradient-to-b from-background to-muted/30 py-20">
        <div className="container max-w-4xl text-center">
          <div className="mb-4 inline-block rounded-full bg-emerald-500/10 px-3 py-1 text-xs font-semibold uppercase tracking-wider text-emerald-700">
            For [audience A] · [Delivery promise]
          </div>
          <h1 className="text-4xl font-bold tracking-tight sm:text-6xl">
            [Hero headline for audience A.]
          </h1>
          <p className="mt-6 text-lg text-muted-foreground sm:text-xl">
            [Hero subhead — describe how the merchant works for this audience.]
          </p>
          <div className="mt-8">
            <SelfServeForm fixedServiceId="service-a" />
            <p className="mt-3 text-xs text-muted-foreground">
              [Trust line — free preview · no signup · etc.]
            </p>
          </div>
        </div>
      </section>

      <section id="why" className="container py-16">
        <div className="mx-auto max-w-3xl text-center">
          <h2 className="text-3xl font-bold tracking-tight">[Why this works.]</h2>
          <p className="mt-3 text-muted-foreground">[Subhead.]</p>
        </div>
        <div className="mx-auto mt-10 grid max-w-5xl gap-4 md:grid-cols-2 lg:grid-cols-4">
          {STATS.map((s) => (
            <Card key={s.figure} className="overflow-hidden">
              <CardContent className="space-y-2 p-6">
                <div className="text-4xl font-bold tracking-tight text-primary">{s.figure}</div>
                <div className="text-sm font-semibold">{s.label}</div>
                <p className="text-sm text-muted-foreground">{s.detail}</p>
                <div className="pt-1 text-[11px] uppercase tracking-wider text-muted-foreground">Source: {s.source}</div>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      <section id="samples" className="container py-16">
        <div className="mx-auto max-w-3xl text-center">
          <h2 className="text-3xl font-bold tracking-tight">Drag the slider.</h2>
          <p className="mt-3 text-muted-foreground">
            Every "after" was generated by the exact pipeline that runs on your submission.
          </p>
        </div>
        <div className="mt-10 grid gap-8 md:grid-cols-2 lg:grid-cols-3">
          {samples.map((s) => (
            <div key={s.id} className="space-y-2">
              <BeforeAfterComparator beforeUrl={s.before} afterUrl={s.after} />
              <p className="text-sm text-muted-foreground">{s.caption}</p>
            </div>
          ))}
        </div>
      </section>

      <section id="pricing" className="border-t bg-muted/30 py-16">
        <div className="container">
          <div className="mx-auto max-w-2xl text-center">
            <h2 className="text-3xl font-bold tracking-tight">Pricing.</h2>
            <p className="mt-3 text-muted-foreground">Pay once per submission. No subscriptions.</p>
          </div>
          <div className="mx-auto mt-10 grid max-w-4xl gap-6 md:grid-cols-3">
            <Card><CardContent className="space-y-2 p-6">
              <div className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Standard</div>
              <div className="text-3xl font-bold">$[X]</div>
              <p className="text-sm text-muted-foreground">[Standard tier description.]</p>
            </CardContent></Card>
            <Card className="border-primary"><CardContent className="space-y-2 p-6">
              <div className="text-xs font-semibold uppercase tracking-wider text-primary">+ Premium</div>
              <div className="text-3xl font-bold">$[X]</div>
              <p className="text-sm text-muted-foreground">[Premium tier description.]</p>
            </CardContent></Card>
            <Card><CardContent className="space-y-2 p-6">
              <div className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Rush</div>
              <div className="text-3xl font-bold">$[X]</div>
              <p className="text-sm text-muted-foreground">[Rush tier description.]</p>
            </CardContent></Card>
          </div>
        </div>
      </section>

      <section id="faq" className="container py-16">
        <div className="mx-auto max-w-2xl text-center">
          <h2 className="text-3xl font-bold tracking-tight">Common questions.</h2>
        </div>
        <div className="mx-auto mt-10 max-w-4xl">
          <FAQ audience="audience-a" />
        </div>
      </section>
    </>
  );
}
