import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { SeoBootstrapPanel } from "@/components/admin/seo-bootstrap-panel";

export const dynamic = "force-dynamic";
export const revalidate = 0;

const ENV_CHECKS: { name: string; key: string; required: boolean; help: string }[] = [
  {
    name: "App URL",
    key: "NEXT_PUBLIC_APP_URL",
    required: true,
    help: "Drives sitemap loc=, robots Sitemap=, OG image URLs, and JSON-LD canonicals. Per-merchant.",
  },
  {
    name: "IndexNow key",
    key: "NEXT_PUBLIC_INDEXNOW_KEY",
    required: true,
    help: "Per-merchant key generated by scripts/generate-indexnow-key.mjs. The matching public/<key>.txt file must be deployed.",
  },
  {
    name: "GSC OAuth client ID",
    key: "ZILLA_GSC_OAUTH_CLIENT_ID",
    required: true,
    help: "Shared HQ credential. See ZILLA_HQ_SETUP.md to provision once.",
  },
  {
    name: "GSC OAuth client secret",
    key: "ZILLA_GSC_OAUTH_CLIENT_SECRET",
    required: true,
    help: "Shared HQ credential.",
  },
  {
    name: "GSC refresh token",
    key: "ZILLA_GSC_OAUTH_REFRESH_TOKEN",
    required: true,
    help: "Shared HQ credential. Authorizes the bootstrap to add child URL-prefix properties under the verified zilla.so Domain property.",
  },
  {
    name: "Bing Webmaster API key",
    key: "ZILLA_BING_WEBMASTER_API_KEY",
    required: true,
    help: "Shared HQ credential from Bing Webmaster → Settings → API Access.",
  },
  {
    name: "Google verification meta tag",
    key: "NEXT_PUBLIC_GOOGLE_VERIFICATION",
    required: false,
    help: "Optional fallback if HQ Domain inheritance fails. Per-merchant URL-prefix verification token.",
  },
];

export default async function AdminSeoPage() {
  const presence = ENV_CHECKS.map((c) => ({
    ...c,
    set: Boolean(process.env[c.key]),
  }));

  const allRequiredSet = presence.filter((p) => p.required).every((p) => p.set);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold">SEO bootstrap</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          One-click registration of this merchant with Google Search
          Console + Bing Webmaster + IndexNow. Idempotent — safe to
          re-run any time. The Inngest cron also fires daily at 04:00
          UTC as a safety net.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Configuration</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="mb-4 text-xs text-muted-foreground">
            All required env vars must be set in Vercel for the
            bootstrap to succeed. See{" "}
            <a className="underline" href="/ZILLA_HQ_SETUP.md">
              ZILLA_HQ_SETUP.md
            </a>{" "}
            for the one-time HQ credential provisioning, and{" "}
            <a className="underline" href="/SEO.md">
              SEO.md
            </a>{" "}
            for the per-merchant flow.
          </p>
          <div className="space-y-2 text-sm">
            {presence.map((p) => (
              <div
                key={p.key}
                className="flex items-start gap-3 rounded-md border bg-card p-3"
              >
                <span
                  className={`mt-0.5 inline-block h-2 w-2 shrink-0 rounded-full ${
                    p.set
                      ? "bg-emerald-500"
                      : p.required
                        ? "bg-red-500"
                        : "bg-amber-500"
                  }`}
                />
                <div className="min-w-0 flex-1">
                  <div className="flex items-baseline justify-between gap-2">
                    <span className="font-medium">{p.name}</span>
                    <code className="text-xs text-muted-foreground">{p.key}</code>
                  </div>
                  <p className="mt-1 text-xs text-muted-foreground">{p.help}</p>
                </div>
                <span
                  className={`rounded px-2 py-0.5 text-xs font-semibold ${
                    p.set
                      ? "bg-emerald-100 text-emerald-800"
                      : p.required
                        ? "bg-red-100 text-red-800"
                        : "bg-amber-100 text-amber-800"
                  }`}
                >
                  {p.set ? "set" : p.required ? "missing" : "optional"}
                </span>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      <SeoBootstrapPanel ready={allRequiredSet} />
    </div>
  );
}
