/**
 * IndexNow client. Submits URLs to IndexNow's central endpoint, which
 * forwards them to Bing, Yandex, Naver, Seznam, and any other
 * participating engines.
 *
 * Each merchant has its own per-host key — generated by
 * scripts/generate-indexnow-key.mjs and stored at
 * public/<key>.txt + NEXT_PUBLIC_INDEXNOW_KEY in env.
 *
 * Reused across the bootstrap flow (one-shot from `seoBootstrap`) and
 * an optional periodic re-ping cron when content lands in batches.
 */

const ENDPOINT = "https://api.indexnow.org/indexnow";
const CHUNK = 1000;

export interface IndexNowConfig {
  // Full URL of the merchant — e.g. "https://xyz.zilla.so" — used for
  // host computation and key location.
  appUrl: string;
  // The per-merchant IndexNow key from NEXT_PUBLIC_INDEXNOW_KEY.
  key: string;
}

export function readConfigFromEnv(): IndexNowConfig | null {
  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? process.env.NEXT_PUBLIC_SITE_URL;
  const key = process.env.NEXT_PUBLIC_INDEXNOW_KEY;
  if (!appUrl || !key) return null;
  return { appUrl, key };
}

/**
 * Fetch the merchant's live sitemap and extract every <loc> URL.
 * Used by the bootstrap to submit everything in one shot.
 */
export async function fetchSitemapUrls(appUrl: string): Promise<string[]> {
  const sitemapUrl = `${appUrl.replace(/\/$/, "")}/sitemap.xml`;
  const res = await fetch(sitemapUrl);
  if (!res.ok) {
    throw new Error(`Sitemap fetch failed: HTTP ${res.status} at ${sitemapUrl}`);
  }
  const xml = await res.text();
  return [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]);
}

export async function submit(config: IndexNowConfig, urls: string[]): Promise<{ submitted: number; chunks: { status: number; body: string }[] }> {
  if (urls.length === 0) return { submitted: 0, chunks: [] };

  const host = new URL(config.appUrl).hostname;
  const keyLocation = `${config.appUrl.replace(/\/$/, "")}/${config.key}.txt`;
  const chunks: { status: number; body: string }[] = [];
  let submitted = 0;

  for (let i = 0; i < urls.length; i += CHUNK) {
    const slice = urls.slice(i, i + CHUNK);
    const res = await fetch(ENDPOINT, {
      method: "POST",
      headers: { "Content-Type": "application/json; charset=utf-8" },
      body: JSON.stringify({
        host,
        key: config.key,
        keyLocation,
        urlList: slice,
      }),
    });
    const body = await res.text().catch(() => "");
    chunks.push({ status: res.status, body: body.slice(0, 500) });
    submitted += slice.length;
  }

  return { submitted, chunks };
}
