import { signedR2Url } from "@/lib/r2";
import type { Audience } from "@/lib/services";

/**
 * Real before/afters generated by our own pipeline (fal.ai Nano Banana Pro
 * /edit endpoint) and stored in R2. Keys live here, URLs are signed at render
 * time so the bucket stays private.
 *
 * Regenerate via:
 *   node --env-file=.env.local scripts/generate-service-samples.mjs
 */
interface Sample {
  id: string;
  beforeKey: string;
  afterKey: string;
  caption: string;
  audience: Audience;
  /**
   * Whether to surface this sample on the audience-hub pages (/agents,
   * /renovate). When false, it can still appear on its own service detail
   * page (/services/<id>). Defaults to true.
   */
  showOnHubs?: boolean;
}

const SAMPLES: Sample[] = [
  {
    id: "photo-staging",
    beforeKey: "samples/services/photo-staging-before.jpg",
    afterKey: "samples/services/photo-staging-after.jpg",
    caption: "Photo Staging — sparse living room → fully staged",
    audience: "agents", // listing prep — not on the homeowner side
  },
  {
    id: "twilight-exterior",
    beforeKey: "samples/services/twilight-exterior-before.jpg",
    afterKey: "samples/services/twilight-exterior-after.jpg",
    caption: "Twilight Exterior — daytime → golden hour",
    audience: "agents",
  },
  {
    id: "curb-appeal",
    beforeKey: "samples/services/curb-appeal-before.jpg",
    afterKey: "samples/services/curb-appeal-after.jpg",
    caption: "Curb Appeal — bare yard → manicured landscape",
    // Renovate-only: curb-appeal is a homeowner value-add, not a listing-
    // photo service. Lives on /renovate (drag-the-slider) + the dedicated
    // /services/curb-appeal detail page; doesn't clutter /agents.
    audience: "renovate",
  },
  {
    id: "pool-mockup",
    beforeKey: "samples/services/pool-mockup-before.jpg",
    afterKey: "samples/services/pool-mockup-after.jpg",
    caption: "Pool Mockup — empty backyard → in-ground pool (satellite view)",
    audience: "renovate",
  },
  {
    id: "solar-mockup",
    beforeKey: "samples/services/solar-mockup-before.jpg",
    afterKey: "samples/services/solar-mockup-after.jpg",
    caption: "Solar Mockup — bare roof → solar array (satellite view)",
    audience: "renovate",
  },
];

const WEEK_SECONDS = 60 * 60 * 24 * 7;

export async function getSampleBeforeAfters(audience?: Audience): Promise<
  { id: string; before: string; after: string; caption: string }[]
> {
  const filtered = audience
    ? SAMPLES.filter(
        (s) =>
          (s.audience === audience || s.audience === "both") &&
          s.showOnHubs !== false,
      )
    : SAMPLES;

  if (!process.env.R2_ACCOUNT_ID) {
    return filtered.map((s) => ({
      id: s.id,
      before: `https://placehold.co/1200x900/e2e8f0/475569?text=${encodeURIComponent("Before " + s.caption)}`,
      after: `https://placehold.co/1200x900/1f2937/f8fafc?text=${encodeURIComponent("After " + s.caption)}`,
      caption: s.caption,
    }));
  }

  return Promise.all(
    filtered.map(async (s) => ({
      id: s.id,
      before: await signedR2Url(s.beforeKey, WEEK_SECONDS),
      after: await signedR2Url(s.afterKey, WEEK_SECONDS),
      caption: s.caption,
    })),
  );
}

/**
 * Look up a single sample by service id (for /services/<id> detail pages).
 * Returns null if no sample exists for that service.
 */
export async function getSampleForService(
  serviceId: string,
): Promise<{ id: string; before: string; after: string; caption: string } | null> {
  const s = SAMPLES.find((x) => x.id === serviceId);
  if (!s) return null;
  if (!process.env.R2_ACCOUNT_ID) {
    return {
      id: s.id,
      before: `https://placehold.co/1200x900/e2e8f0/475569?text=${encodeURIComponent("Before " + s.caption)}`,
      after: `https://placehold.co/1200x900/1f2937/f8fafc?text=${encodeURIComponent("After " + s.caption)}`,
      caption: s.caption,
    };
  }
  return {
    id: s.id,
    before: await signedR2Url(s.beforeKey, WEEK_SECONDS),
    after: await signedR2Url(s.afterKey, WEEK_SECONDS),
    caption: s.caption,
  };
}
