import Link from "next/link";
import { BeforeAfterComparator } from "@/components/marketing/before-after-comparator";
import { FAQ } from "@/components/marketing/faq";
import { SelfServeForm } from "@/components/marketing/self-serve-form";
import { Card, CardContent } from "@/components/ui/card";
import { getSampleBeforeAfters } from "@/lib/samples";

export const dynamic = "force-dynamic";
export const metadata = { title: "Restay for Hosts — Airbnb listing optimization" };

const STATS = [
  {
    figure: "60%",
    label: "of listings haven't been updated in over a year",
    detail:
      "Most hosts set up their Airbnb once and don't return. Title, description, photos, and price drift as the market moves.",
    source: "Restay analysis",
  },
  {
    figure: "20%",
    label: "median weekly revenue lift from a listing tune-up",
    detail:
      "Across optimization studies, repriced + rewritten + restyled listings show ~20% revenue lift in the 30 days after refresh.",
    source: "AirDNA / industry studies",
  },
  {
    figure: "$20–40/mo",
    label: "what Guesty / Hospitable charge — for less",
    detail:
      "Their core monthly subscription doesn't rewrite your listing or restyle your photos. We do that once, for less than a month of theirs.",
    source: "Public pricing pages",
  },
  {
    figure: "<4h",
    label: "delivery on Standard",
    detail:
      "Rush goes to 24h. If we miss the SLA, you get refunded automatically.",
    source: "Restay SLA",
  },
];

export default async function HostsPage() {
  const samples = await getSampleBeforeAfters("host");
  return (
    <>
      <section className="border-b bg-gradient-to-b from-background to-muted/30 py-20">
        <div className="container max-w-4xl text-center">
          <div className="mb-4 inline-block rounded-full bg-emerald-500/10 px-3 py-1 text-xs font-semibold uppercase tracking-wider text-emerald-700">
            For Airbnb hosts · Delivered in under 4 hours
          </div>
          <h1 className="text-4xl font-bold tracking-tight sm:text-6xl">
            Rewrite your listing. Restyle your photos. Reprice your nights.
          </h1>
          <p className="mt-6 text-lg text-muted-foreground sm:text-xl">
            Paste your Airbnb URL — we'll generate a free 60-second audit with one
            restyled photo and a comp-pricing snapshot. Pay only when you order the full Tune-Up.
          </p>
          <div className="mt-8">
            <SelfServeForm fixedServiceId="listing-tune-up" />
            <p className="mt-3 text-xs text-muted-foreground">
              Edit-only photos · No subscription · No PMS lock-in
            </p>
            <p className="mt-4 text-sm">
              Want a free 10-second score first?{" "}
              <Link href="/grade" className="font-semibold text-primary underline">
                Grade your listing →
              </Link>
            </p>
          </div>
        </div>
      </section>

      <section id="samples" className="container py-12 sm:py-16">
        <div className="mx-auto max-w-3xl text-center">
          <h2 className="text-3xl font-bold tracking-tight">Drag the slider.</h2>
          <p className="mt-3 text-muted-foreground">
            Same source photo on the left, our edit on the right — generated by the same pipeline that runs on your listing.
          </p>
        </div>
        <div className="mt-10 grid gap-8 md:grid-cols-2 lg:grid-cols-3">
          {samples.map((s) => (
            <div key={s.id} className="space-y-2">
              <BeforeAfterComparator beforeUrl={s.before} afterUrl={s.after} />
              <p className="text-sm text-muted-foreground">{s.caption}</p>
            </div>
          ))}
        </div>
      </section>

      <section id="why" className="container py-16">
        <div className="mx-auto max-w-3xl text-center">
          <h2 className="text-3xl font-bold tracking-tight">
            Most listings stop optimizing the day they launch.
          </h2>
          <p className="mt-3 text-muted-foreground">
            We re-run the work in one sweep — no monthly contract, no PMS migration.
          </p>
        </div>
        <div className="mx-auto mt-10 grid max-w-5xl gap-4 md:grid-cols-2 lg:grid-cols-4">
          {STATS.map((s) => (
            <Card key={s.figure} className="overflow-hidden">
              <CardContent className="space-y-2 p-6">
                <div className="text-4xl font-bold tracking-tight text-primary">
                  {s.figure}
                </div>
                <div className="text-sm font-semibold">{s.label}</div>
                <p className="text-sm text-muted-foreground">{s.detail}</p>
                <div className="pt-1 text-[11px] uppercase tracking-wider text-muted-foreground">
                  Source: {s.source}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      <section id="pricing" className="border-t bg-muted/30 py-16">
        <div className="container">
          <div className="mx-auto max-w-2xl text-center">
            <h2 className="text-3xl font-bold tracking-tight">Pricing.</h2>
            <p className="mt-3 text-muted-foreground">
              One-time per listing. No subscriptions, no per-photo fees.
            </p>
          </div>
          <div className="mx-auto mt-10 grid max-w-4xl gap-6 md:grid-cols-3">
            <Card>
              <CardContent className="space-y-2 p-6">
                <div className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                  Listing Tune-Up
                </div>
                <div className="text-3xl font-bold">$79</div>
                <p className="text-sm text-muted-foreground">
                  Rewritten title + description, 10 edited photos, 30-day pricing report.
                </p>
              </CardContent>
            </Card>
            <Card className="border-primary">
              <CardContent className="space-y-2 p-6">
                <div className="text-xs font-semibold uppercase tracking-wider text-primary">
                  Premium
                </div>
                <div className="text-3xl font-bold">$149</div>
                <p className="text-sm text-muted-foreground">
                  Tune-Up + A/B title, 20 photos, seasonal pricing calendar.
                </p>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="space-y-2 p-6">
                <div className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                  Rush
                </div>
                <div className="text-3xl font-bold">$129</div>
                <p className="text-sm text-muted-foreground">
                  Standard with priority queue. 24-hour turnaround.
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      <section id="faq" className="container py-16">
        <div className="mx-auto max-w-2xl text-center">
          <h2 className="text-3xl font-bold tracking-tight">Common questions.</h2>
        </div>
        <div className="mx-auto mt-10 max-w-4xl">
          <FAQ audience="host" />
        </div>
      </section>
    </>
  );
}
